# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7122e01cee18444c1640695461813fdf5803319159d57adc031c7f7fa80ac5ac12c7f65a331e8d67a11ff0aa9cb10014df71637501a64a440efa84b913997f6

test:
  secret_key_base: 9af531f764c4d5d8e31d4d51a202be140cb077b468b5437485843fd09ad9ae399ea6c355d16ab8f0bb2b9046c47651fe0ae28a4f916f952418491fb05e8771c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
